version: "3"

services:
  database:
    image: postgres:alpine
    container_name: crud_actix_database
    restart: always
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=5432
    ports:
      - $POSTGRES_PORT:5432
    env_file:
      - ./.env
    networks:
      - crud_actix

networks:
  crud_actix:
    driver: bridge